version: '3.8'
services:
  payload-1:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - content:/app/content
    depends_on:
      - mongo
    env_file:
      - .env.docker

  payload-2:
    build: .
    ports:
      - '3002:3000'
    volumes:
      - content:/app/content
    depends_on:
      - mongo
    env_file:
      - .env.docker

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  nginx:
    image: nginx:latest
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payload-1
      - payload-2

volumes:
  data:
  content:
