services:
  payload-prod:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - content:/app/content
    depends_on:
      - mongo
    env_file:
      - .env.docker

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  content:
